function draw_link = draw_link(pos_1,pos_2)
% draw the link
plot3([pos_1(1) pos_2(1)],[pos_1(2) pos_2(2)],[pos_1(3) pos_2(3)],'Linewidth',5,'Marker','o',...
                               'MarkerSize',7,...
                               'MarkerEdgeColor','b',...
                               'MarkerFaceColor',[0.1,0.1,0.1]);
end

